/*
 * Copyright (c) 2012, 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package org.glassfish.grizzly.thrift.client;

import org.apache.thrift.TServiceClient;

/**
 * Thrift client callback interface
 *
 * User should implement this interface in order to execute custom thrift service.
 *
 * Example of use:
 * {@code
 * Integer result = calculatorThriftClient.execute(new ThriftClientCallback<Calculator.Client, Integer>() {
 *
 *         public Integer call(Calculator.Client client) throws TException {
 *              return client.add(1, 2);
 *         }
 *     });
 * }
 * "calculatorThriftClient" is an instance of {@link GrizzlyThriftClient}(For more information, please see {@link GrizzlyThriftClient}'s javadoc).
 * "Calculator.Client" is custom thrift client which has been generated by thrift.
 * "Integer" is custom result type.
 *
 * @author Bongjae Chang
 */
public interface ThriftClientCallback<T extends TServiceClient, U> {

    U call(final T client) throws Exception;
}
